# -*- coding: utf-8 -*-
"""despliegue_clasificacion_pf.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Sg2rC4IotOgPZxlyT96OMmGQE4pUbgxW

# Despliegue

- Cargamos el modelo
- Cargamos los datos futuros
- Preparar los datos futuros
- Aplicamos el modelo para la predicción
"""

#Cargamos librerías principales
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

#Cargamos el modelo
import pickle
filename = 'modelo-clasificacion-svm.pkl'
modeloSVM, variables, labelencoder = pickle.load(open(filename, 'rb'))

#CUANDO YA SE TENGAN LOS DATOS => SE COMENTAN, YA QUE SE USARA EL FORMULARIO Y NO EL CSV
#Cargamos los datos futuros
#data = pd.read_csv("datos_futuro.csv")
#data.head()

# INTERFAZ GRAFICA (SE DEJA VACIA) => PRIMERO HACER PREDICCION
import streamlit as st

st.title('Predicción de éxito para prendas de una empresa textil de Medellín')

color = st.selectbox('Color', ["NEGRO","BEIGE", "BLANCO","SAHARA", "ROSADO", "AZUL", "GRIS", "VARIOS"])
talla = st.selectbox('Talla', ["3XS", "2XS", "XS", "S", "M", "L", "XL", "2XL", "3XL", "4XL", "UNI", "PEQ", "GRAN"])
tipo_prenda = st.selectbox('Tipo de Prenda', ["F", "STA", "SXA", "C", "B", "CH", "STB", "S", "M", "MD", "CA", "EX", "FL", "TA", "CN", "T", "BE", "E", "MA", "H", "G", "PL"])


#Dataframe
datos = [[color, talla, tipo_prenda]]
data = pd.DataFrame(datos, columns=['color', 'talla','tipo_prenda']) #Dataframe con los mismos nombres de variables

#Se realiza la preparación
data_preparada=data.copy()

print(data_preparada.columns)

#En despliegue drop_first= False
data_preparada = pd.get_dummies(data_preparada, columns=['color', 'talla', 'tipo_prenda'], drop_first=False, dtype=int)
data_preparada.head()

#Se adicionan las columnas faltantes
data_preparada=data_preparada.reindex(columns=variables,fill_value=0)
data_preparada.head()

"""# Predicciones

Importancia: El modelo presenta un error del N% => La predicción no es perfecta.
"""

#Hacemos la predicción con el SVM
Y_pred = modeloSVM.predict(data_preparada)
print(Y_pred)

data['prediccion_SVM']=labelencoder.inverse_transform(Y_pred)
data.head()

#$data['Prediccion']=Y_pred
#data.head()

#Preddicones finales
data